# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'


variables:
  JAVA_HOME: 'Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home'

steps:

- task: Gradle@2
  displayName: 'Gradle Build file'
  inputs:
    gradleWrapperFile: 'gradlew'
    architecture: 'x64'
    workingDirectory: ''
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    outputDirectory: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release'
    gradleOptions: '-Xmx3072m -Xms3072m -XX:NewSize=1024m -XX:MaxNewSize=1024m -XX:+UseParallelGC'
    testResultsFiles: '**/TEST-*.xml'
    analysisResultsFiles: '**/reports/*-checkstyle.xml,**/reports/*-findbugs.xml,**/reports/*-pmd.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()


#Your build pipeline references an undefined variable named ‘apkName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

- task: AndroidSigning@3
  displayName: 'Build and sign APK'
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: smpleapp
    apksignerKeystorePassword: 123456
    apksignerKeystoreAlias: SampleCICDpipeline
    apksignerKeyPassword: 123456
    buildType: 'Release'
    androidSigningScheme: 'apkSignature'
    signingConfigName: 'myConfig'
    apksignerArguments: '--out $(build.artifactStagingDirectory)/app-signed.apk' #$(apkName)-signed.apk


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: android'
  inputs:
    #targetPath: '$(Build.ArtifactStagingDirectory)'
    #targetPath: '$(Build.ArtifactStagingDirectory)/android/$(apkName)-signed.apk'
    PathtoPublish: '$(build.artifactstagingdirectory)'
    publishLocation: 'Container'
    ArtifactName: 'android'
    condition: succeededOrFailed()
 
- task: AppCenterDistribute@3
  displayName: Distribute release to App Center
  inputs:
    serverEndpoint: 'UpdatedBuild'
    appSlug: 'narasimharaoy.in-mouritech.com/SampleCICDpipeline'
    releaseNotesOption: 'input'
    appFile: '$(build.artifactStagingDirectory)/app-signed.apk'
    #appFile: '**/*.apk'
    # **/*.apk
    #artifactsPattern: '**/*.apk'
    releaseNotesInput: 'New features and bug fixes'
    destinationType: 'groups'
    distributionGroup: 'MyAppDemo'
    isMandatory: true
    distributionGroupId: 'fbc8c624-5cbd-42c6-bf52-f712edf94605'
    filePattern: '$(build.artifactstagingdirectory)/*.apk'
    #filePattern: '**/app/build/outputs/apk/release/*.apk' 
  enabled: true
  condition: succeededOrFailed()


