# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'


variables:
  JAVA_HOME: 'Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home'

steps:
- task: Gradle@2
  displayName: 'Build and sign APK'
  inputs:
    gradleWrapperFile: 'gradlew'
    architecture: 'x64'
    workingDirectory: ''
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    gradleOptions: '-Xmx3072m'
    androidSigningScheme: 'apkSignature'
    signingConfigName: 'release'
    keystoreFile: '/Users/narasimharaoy/KeystorePath/newsapp_keystorepath'
    keystorePassword: '$(123456)'
    keyAlias: 'key0'
    keyPassword: '$(123456)'
    testResultsFiles: '**/TEST-*.xml'
    buildType: 'Release'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
 
- task: AppCenterDistribute@3
  displayName: Distribute release to App Center
  inputs:
    serverEndpoint: 'UpdatedBuild'
    appSlug: 'narasimharaoy.in-mouritech.com/SampleCICDpipeline'
    releaseNotesOption: 'input'
    appFile: '**/*.apk'
    artifactsPattern: '**/*.apk'
    releaseNotesInput: 'New features and bug fixes'
    destinationType: 'groups'
    distributionGroup: 'MyAppDemo'
    isMandatory: true
    distributionGroupId: 'fbc8c624-5cbd-42c6-bf52-f712edf94605'
    filePattern: '$(build.artifactstagingdirectory)/*.apk'
  enabled: true
  condition: succeededOrFailed()




    