# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'


variables:
  JAVA_HOME: 'Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home'

steps:
- task: Gradle@2
  inputs:
    architecture: 'x64'
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'